version: 2.1

orbs:
  aws-s3: circleci/aws-s3@1.0.15
  heroku: circleci/heroku@1.0.1
  python: circleci/python@0.2.1

executors:
  test-and-lint-exc:
    docker:
      - image: csmcallister/node-pa11y-python
  deploy-exc:
    docker:
      - image: circleci/python:3.7.4

jobs:
  lint:
    executor: test-and-lint-exc
  
    steps:
      - checkout

      - run:
          name: flake8
          command: |
            sudo python3.7 -m venv env
            . env/bin/activate
            sudo pip install -r requirements.txt
            sudo pip install -e .
            flake8

  test:
    executor: test-and-lint-exc
      
    steps:
      - checkout
      
      - aws-s3/copy:
          from: "s3://${BUCKET_NAME}/data.json"
          to: "./feda11y/static/data.json"

      - aws-s3/copy:
          from: "s3://${BUCKET_NAME}/hist.json"
          to: "./feda11y/static/hist.json"
      
      - run:
          name: test
          command: |
            sudo python3.7 -m venv env
            . env/bin/activate
            sudo pip install -r requirements.txt
            sudo pip install -e .
            sudo pytest

      - run:
          name: pa11y
          command: |
            flask run & sleep 5 && sudo /node_modules/.bin/pa11y-ci --config .pa11yci
  
  deploy:
    executor: deploy-exc
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - aws-s3/copy:
          from: "s3://${BUCKET_NAME}/data.json"
          to: "./feda11y/static/data.json"
      - aws-s3/copy:
          from: "s3://${BUCKET_NAME}/hist.json"
          to: "./feda11y/static/hist.json"
      - run:
          name: Deploy Master to Heroku
          command: |
            git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master
  

workflows:
  version: 2
  lint-and-test: 
    jobs:
      - lint
      - test:
          requires:
            - lint
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: master